### ISSUE TITLE
Not possible to define fontFace with local()

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluent-ui-react#1454]
## Bug Report

I am trying to define `@font-face` with `local()`:

```css
  @font-face { 
    font-family: MyHelvetica; 
    src: local("Helvetica Neue Bold"), local("HelveticaNeue-Bold"),
        url(MgOpenModernaBold.ttf);
    font-weight: bold; 
  } 
```

It will not be properly handled if I will try to use `paths` and will cause infinite loop:

```js
{
  name: "Segoe UI Local",
  paths: [
     'Segoe UI Light',
     'SegoeUI-Light',
     'Segoe WP Light',
   ],
}
```

The infinite loop will be caused because Fela in `renderer.renderFont()` expects `files`:
> It must have one of the following file extensions: .woff, .woff2, .eof, .ttf or .svg

#### Workaround

We are passing `font.style` in `this.topLevelFelaRenderer.renderFont(font.name, font.paths, font.style)` so I can do this:

```jsx
  {
    name: "Segoe UI Local",
    paths: [],
    style: {
      localAlias: [
        'Segoe UI Light',
        'SegoeUI-Light',
        'Segoe WP Light',
      ],
    }
  },
```

However, it will cause TS error `Error:(8, 7) TS2322: Type 'string[]' is not assignable to type 'string'.` because we expect plain strings in `style`.

### Solution

Expose `localAliases` in `FontFace` type and pass it down Fela renderer.

### Version
0.32.0
