### ISSUE TITLE
[RFC] Build process on CircleCI is taking too long

### ISSUE THREAD

**Issue by mnajdova** [microsoft/fluent-ui-react#246]
### Problem description
The build process on CircleCI is taking too long (from 5:30 - 7:30 mins approx). We should think of ways of how to improve this time.

### Proposed solution
From @levithomason: CircleCi gives us a max parallelism of 4. This allows us to split tests up across 4 machines at once. We can drastically reduce the amount of time for testing if we use this feature.

I have tried this approach but we kind a hit several problems
- Just using the parallelism on the build job, causes blocking on other PRs build, as we were occupying all machines available to us. (Maybe there is some other explanation for this, but it seems that this was the problem.)
- I tried distinguishing the build, test and lint aspects in three different jobs in the following manner:
```
version: 2
general:
  branches:
    ignore:
      - gh-pages
jobs:
  build:
    docker:
      - image: circleci/node:8
    parallelism: 4
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    steps:
      - run:
          name: Update yarn
          command: |
            # remove default yarn
            sudo rm -rf $(dirname $(which yarn))/yarn*
            # download latest
            rm -rf ~/.yarn
            curl -o- -L https://yarnpkg.com/install.sh | bash
            echo 'export PATH="${PATH}:${HOME}/.yarn/bin"' >> $BASH_ENV
      - checkout
      # because we don't invoke npm (we use yarn) we need to add npm bin to PATH manually
      - run:
          name: Add npm bin to PATH
          command: echo 'export PATH="${PATH}:$(npm bin)"' >> $BASH_ENV
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - .yarn-cache
            - node_modules

  lint:
    docker:
      - image: circleci/node:8
    parallelism: 4
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    steps:
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Prettier
          command: yarn prettier

  test:
    docker:
      - image: circleci/node:8
    parallelism: 4
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    steps:
      - run:
          name: Unit Tests
          command: yarn test --maxWorkers=4
      - run:
          name: Report coverage
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Visual Tests
          command: yarn test:visual

workflows:
  version: 2
  build_lint_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
```
havnig the test and lint jobs be dependent on the build, but this didn't work, as these two jobs were throwing the error:

yarn run v1.9.4
error Couldn't find a package.json file in "/home/circleci/project"

If anyone has an idea why this is happening I would be keen on investigating this further.
